/*Assign VISIT_OCCURRENCE_ID to all claim lines*/
/*********************************************************************/

/*~~~TEST FOR NULLS WITH VISIT_OCCURRENCE_ID~~~*/

IF OBJECT_ID('tempdb..@result_temp_aavi', 'U') IS NOT NULL DROP TABLE @result_temp_aavi
CREATE TABLE @result_temp_aavi WITH (LOCATION = USER_DB, DISTRIBUTION = HASH(HVID)) AS


SELECT CL.STEM_ID,
		CL.CLAIM_ID,
		CL.HVID,
		CL.VISIT_START_DATE AS DATE_SERVICE,
		CL.VISIT_END_DATE AS DATE_SERVICE_END,
		CL.PROV_RENDERING_NPI,
		CL.CLAIM_TYPE_NEW,
		AV.CLAIM_TYPE_NEW AS VISIT_TYPE,
		AV.VISIT_START_DATE,
		AV.VISIT_END_DATE,
		AV.PROV_RENDERING_NPI AS VISIT_PROVIDER_ID,
		AV.VISIT_OCCURRENCE_ID,
		CASE
			WHEN CL.CLAIM_TYPE_NEW = 'IP' AND AV.CLAIM_TYPE_NEW = 'IP'
				THEN VISIT_OCCURRENCE_ID
			WHEN CL.CLAIM_TYPE_NEW = 'LTC' AND AV.CLAIM_TYPE_NEW = 'LTC'
				THEN VISIT_OCCURRENCE_ID
			WHEN CL.CLAIM_TYPE_NEW = 'ER'
				THEN (
					CASE
						WHEN AV.CLAIM_TYPE_NEW = 'IP' AND CL.VISIT_START_DATE > AV.VISIT_START_DATE
							THEN VISIT_OCCURRENCE_ID
						WHEN AV.CLAIM_TYPE_NEW = 'ER' AND CL.VISIT_START_DATE = AV.VISIT_START_DATE
							THEN VISIT_OCCURRENCE_ID
						ELSE NULL
					END
				)
			WHEN CL.CLAIM_TYPE_NEW = 'OP'
				THEN (
					CASE
						WHEN AV.CLAIM_TYPE_NEW = 'IP' AND CL.VISIT_START_DATE >= AV.VISIT_START_DATE
							THEN VISIT_OCCURRENCE_ID
						WHEN AV.CLAIM_TYPE_NEW = 'OP'
							THEN (
								CASE
									WHEN CL.PROV_RENDERING_NPI IS NULL
										THEN VISIT_OCCURRENCE_ID
									WHEN CL.PROV_RENDERING_NPI = AV.PROV_RENDERING_NPI
										THEN VISIT_OCCURRENCE_ID
								END
							)
						ELSE NULL
					END
				)
			ELSE NULL
		END AS VISIT_OCCURRENCE_ID_NEW

FROM @result_claim_lines CL
JOIN @cdm_schema.ALL_VISITS AV
	ON CL.HVID = AV.HVID
	AND CL.VISIT_START_DATE >= AV.VISIT_START_DATE
	AND CL.VISIT_START_DATE <= AV.VISIT_END_DATE
WHERE SUBSTRING(CL.HVID,1,@n_substring) = '@HVID_CHUNK'
