/*CARE SITE*/
/*********************************************************************************************/

IF OBJECT_ID('@cdm_schema.CARE_SITE') IS NOT NULL DROP TABLE @cdm_schema.[CARE_SITE]
CREATE TABLE @cdm_schema.[CARE_SITE]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(CARE_SITE_ID)
)
AS

SELECT CARE_SITE_ID,
	NULL AS CARE_SITE_NAME,
	0 AS PLACE_OF_SERVICE_CONCEPT_ID,
	NULL AS LOCATION_ID,
	CARE_SITE_SOURCE_VALUE,
	NULL AS PLACE_OF_SERVICE_SOURCE_VALUE
FROM (
	SELECT CARE_SITE_SOURCE_VALUE, ROW_NUMBER() OVER (ORDER BY CARE_SITE_SOURCE_VALUE ASC) AS CARE_SITE_ID
	FROM (
		SELECT DISTINCT CARE_SITE_SOURCE_VALUE
		FROM (
			SELECT PROV_FACILITY_NPI AS CARE_SITE_SOURCE_VALUE
			FROM @source_schema.MEDICAL_CLAIMS
			UNION ALL
			SELECT PHARMACY_NPI AS CARE_SITE_SOURCE_VALUE
			FROM @source_schema.PHARMACY_CLAIMS
		) T1
	) T2
) CARE_SITE;
