/*Step 5 - STEM TABLE to CDM*/
/*********************************************************************************************/

/*CONDITION_OCCURRENCE*/

IF OBJECT_ID('@cdm_schema.CONDITION_OCCURRENCE') IS NOT NULL DROP TABLE @cdm_schema.[CONDITION_OCCURRENCE]
CREATE TABLE @cdm_schema.[CONDITION_OCCURRENCE]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(PERSON_ID)
)
AS
SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL)) AS CONDITION_OCCURRENCE_ID,
	S.PERSON_ID AS PERSON_ID,
	S.CONCEPT_ID AS CONDITION_CONCEPT_ID,
	S.START_DATE AS CONDITION_START_DATE,
	cast(NULL as date) AS CONDITION_END_DATE,
	S.TYPE_CONCEPT_ID AS CONDITION_TYPE_CONCEPT_ID,
	S.STOP_REASON,
	S.PROVIDER_ID,
	V.VISIT_OCCURRENCE_ID_NEW AS VISIT_OCCURRENCE_ID,
	S.SOURCE_VALUE AS CONDITION_SOURCE_VALUE,
	S.SOURCE_CONCEPT_ID AS CONDITION_SOURCE_CONCEPT_ID
FROM @cdm_schema.STEM S
JOIN @cdm_schema.FINAL_VISIT_IDS V
  ON S.ID = V.STEM_ID
WHERE DOMAIN_ID = 'CONDITION'
