/*DEVICE_EXPOSURE*/

IF OBJECT_ID('@cdm_schema.DEVICE_EXPOSURE') IS NOT NULL DROP TABLE @cdm_schema.[DEVICE_EXPOSURE]
CREATE TABLE @cdm_schema.[DEVICE_EXPOSURE]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(PERSON_ID)
)
AS
SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL)) AS DEVICE_EXPOSURE_ID,
	PERSON_ID,
	CONCEPT_ID AS DEVICE_CONCEPT_ID,
	START_DATE AS DEVICE_EXPOSURE_START_DATE,
	END_DATE AS DEVICE_EXPOSURE_END_DATE,
	TYPE_CONCEPT_ID AS DEVICE_TYPE_CONCEPT_ID,
	UNIQUE_DEVICE_ID,
	QUANTITY,
	PROVIDER_ID,
	V.VISIT_OCCURRENCE_ID_NEW AS VISIT_OCCURRENCE_ID,
	SOURCE_VALUE AS DEVICE_SOURCE_VALUE,
	SOURCE_CONCEPT_ID AS DEVICE_SOURCE_CONCEPT_ID
FROM @cdm_schema.STEM S
JOIN @cdm_schema.FINAL_VISIT_IDS V
  ON S.ID = V.STEM_ID
WHERE DOMAIN_ID = 'DEVICE'
