/*DRUG_EXPOSURE*/

IF OBJECT_ID('@cdm_schema.DRUG_EXPOSURE') IS NOT NULL DROP TABLE @cdm_schema.[DRUG_EXPOSURE]
CREATE TABLE @cdm_schema.[DRUG_EXPOSURE]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(PERSON_ID)
)
AS
SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL)) AS DRUG_EXPOSURE_ID,
	PERSON_ID AS PERSON_ID,
	CONCEPT_ID AS DRUG_CONCEPT_ID,
	START_DATE AS DRUG_EXPOSURE_START_DATE,
	CAST(NULL AS DATE) AS DRUG_EXPOSURE_END_DATE,
	TYPE_CONCEPT_ID AS DRUG_TYPE_CONCEPT_ID,
	STOP_REASON,
	REFILLS,
	QUANTITY,
	DAYS_SUPPLY,
	SIG,
	ROUTE_CONCEPT_ID,
	EFFECTIVE_DRUG_DOSE,
	DOSE_UNIT_CONCEPT_ID,
	LOT_NUMBER,
	PROVIDER_ID,
	V.VISIT_OCCURRENCE_ID_NEW AS VISIT_OCCURRENCE_ID,
	SOURCE_VALUE AS DRUG_SOURCE_VALUE,
	SOURCE_CONCEPT_ID AS DRUG_SOURCE_CONCEPT_ID,
	ROUTE_SOURCE_VALUE,
	DOSE_UNIT_SOURCE_VALUE
FROM @cdm_schema.STEM S
LEFT JOIN @cdm_schema.FINAL_VISIT_IDS V
  ON S.ID = V.STEM_ID
WHERE DOMAIN_ID = 'DRUG'
