/*Create FINAL VISIT IDS table*/

IF OBJECT_ID('@cdm_schema.FINAL_VISIT_IDS') IS NOT NULL DROP TABLE @cdm_schema.[FINAL_VISIT_IDS]
CREATE TABLE @cdm_schema.[FINAL_VISIT_IDS]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(STEM_ID)
) AS
SELECT STEM_ID, VISIT_OCCURRENCE_ID_NEW
FROM(
	SELECT *, ROW_NUMBER () OVER (PARTITION BY STEM_ID ORDER BY PRIORITY) AS RN
	FROM (
		SELECT *,
			CASE
				WHEN CLAIM_TYPE_NEW = 'ER'
					THEN (
						CASE
							WHEN VISIT_TYPE = 'IP' AND VISIT_OCCURRENCE_ID_NEW IS NOT NULL
								THEN 1
							WHEN VISIT_TYPE = 'ER' AND VISIT_OCCURRENCE_ID_NEW IS NOT NULL
								THEN 2
							ELSE 99
						END
					)
				WHEN CLAIM_TYPE_NEW = 'OP'
					THEN (
						CASE
							WHEN VISIT_TYPE = 'IP' AND VISIT_OCCURRENCE_ID_NEW IS NOT NULL
								THEN  1
							WHEN VISIT_TYPE = 'OP' AND VISIT_OCCURRENCE_ID_NEW IS NOT NULL
								THEN 2
							ELSE 99
						END
					)
				WHEN CLAIM_TYPE_NEW = 'IP' AND VISIT_TYPE = 'IP' AND VISIT_OCCURRENCE_ID_NEW IS NOT NULL
					THEN 1
				WHEN CLAIM_TYPE_NEW = 'LTC' AND VISIT_TYPE = 'LTC' AND VISIT_OCCURRENCE_ID_NEW IS NOT NULL
					THEN 1
				ELSE 99
			END AS PRIORITY
	FROM @cdm_schema.ASSIGN_ALL_VISIT_IDS
	) T1
) T2
WHERE RN=1
