/*MEASUREMENT*/

IF OBJECT_ID('@cdm_schema.MEASUREMENT') IS NOT NULL DROP TABLE @cdm_schema.[MEASUREMENT]
CREATE TABLE @cdm_schema.[MEASUREMENT]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(PERSON_ID)
)
AS
SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL)) AS MEASUREMENT_ID,
	PERSON_ID,
	CONCEPT_ID AS MEASUREMENT_CONCEPT_ID,
	START_DATE AS MEASUREMENT_DATE,
	START_DATE AS MEASUREMENT_TIME,
	TYPE_CONCEPT_ID AS MEASUREMENT_TYPE_CONCEPT_ID,
	OPERATOR_CONCEPT_ID,
	VALUE_AS_NUMBER,
	VALUE_AS_CONCEPT_ID,
	UNIT_CONCEPT_ID,
	RANGE_LOW,
	RANGE_HIGH,
	PROVIDER_ID,
	V.VISIT_OCCURRENCE_ID_NEW AS VISIT_OCCURRENCE_ID,
	SOURCE_VALUE AS MEASUREMENT_SOURCE_VALUE,
	SOURCE_CONCEPT_ID AS MEASUREMENT_SOURCE_CONCEPT_ID,
	UNIT_SOURCE_VALUE,
	VALUE_SOURCE_VALUE
FROM @cdm_schema.STEM S
JOIN @cdm_schema.FINAL_VISIT_IDS V
  ON S.ID = V.STEM_ID
WHERE DOMAIN_ID = 'MEASUREMENT'
