/*OBSERVATION*/

IF OBJECT_ID('@cdm_schema.OBSERVATION') IS NOT NULL DROP TABLE @cdm_schema.[OBSERVATION]
CREATE TABLE @cdm_schema.[OBSERVATION]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(PERSON_ID)
)
AS
SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL)) AS OBSERVATION_ID,
	PERSON_ID,
	CONCEPT_ID AS OBSERVATION_CONCEPT_ID,
	START_DATE AS OBSERVATION_DATE,
	START_DATE AS OBSERVATION_TIME,
	TYPE_CONCEPT_ID AS OBSERVATION_TYPE_CONCEPT_ID,
	VALUE_AS_NUMBER,
	VALUE_AS_STRING,
	VALUE_AS_CONCEPT_ID,
	QUALIFIER_CONCEPT_ID,
	UNIT_CONCEPT_ID,
	PROVIDER_ID,
	V.VISIT_OCCURRENCE_ID_NEW AS VISIT_OCCURRENCE_ID,
	SOURCE_VALUE AS OBSERVATION_SOURCE_VALUE,
	SOURCE_CONCEPT_ID AS OBSERVATION_SOURCE_CONCEPT_ID,
	UNIT_SOURCE_VALUE,
	QUALIFIER_SOURCE_VALUE
FROM @cdm_schema.STEM S
JOIN @cdm_schema.FINAL_VISIT_IDS V
  ON S.ID = V.STEM_ID
WHERE DOMAIN_ID = 'OBSERVATION'
