/*PAYER_PLAN_PERIOD*/
/*********************************************************************************************/

IF XACT_STATE() = 1 COMMIT; CREATE TABLE  @result_temp_table
  WITH (LOCATION = USER_DB, DISTRIBUTION = HASH(PERSON_ID)) AS

WITH CTE_END_DATES AS (
	SELECT HVID, DATEADD(DAY,-32,EVENT_DATE) AS END_DATE
	FROM (
		SELECT HVID, EVENT_DATE, EVENT_TYPE,
			MAX(START_ORDINAL) OVER (PARTITION BY HVID ORDER BY EVENT_DATE, EVENT_TYPE ROWS UNBOUNDED PRECEDING) AS START_ORDINAL,
			ROW_NUMBER() OVER (PARTITION BY HVID ORDER BY EVENT_DATE, EVENT_TYPE) AS OVERALL_ORD
		FROM (
			SELECT HVID, DATE AS EVENT_DATE, -1 AS EVENT_TYPE, ROW_NUMBER () OVER (PARTITION BY HVID ORDER BY DATE) AS START_ORDINAL
			FROM @source_schema.ENROLLMENT_COVERAGE
			WHERE COVERAGE_IND = 'Y' AND SUBSTRING(HVID,1,@n_substring) = '@HVID_CHUNK'
			UNION ALL
			SELECT HVID, DATEADD(DAY,32,DATE), 1 AS EVENT_TYPE, NULL
			FROM @source_schema.ENROLLMENT_COVERAGE
			WHERE COVERAGE_IND = 'Y' AND SUBSTRING(HVID,1,@n_substring) = '@HVID_CHUNK'
			) RAWDATA
	) E
	WHERE (2 * E.START_ORDINAL - E.OVERALL_ORD = 0)
),
CTE_ENROLL_ENDS AS (
	SELECT ENROLL.HVID,
		ENROLL.DATE AS PAYER_PLAN_PERIOD_START_DATE,
		MIN(E.END_DATE) AS PAYER_PLAN_PERIOD_END_DATE
	FROM @source_schema.ENROLLMENT_COVERAGE ENROLL
		JOIN CTE_END_DATES E
			ON ENROLL.HVID = E.HVID
			AND E.END_DATE >= ENROLL.DATE
	WHERE ENROLL.COVERAGE_IND = 'Y'
	GROUP BY ENROLL.HVID, ENROLL.DATE
)

  SELECT
  		T1.*,
  		'Private Source 17'	AS PAYER_SOURCE_VALUE,
  		NULL AS PLAN_SOURCE_VALUE,
  		NULL AS FAMILY_SOURCE_VALUE
  FROM(
  		SELECT P.PERSON_ID,
  			T2.PAYER_PLAN_PERIOD_START_DATE,
  			T2.PAYER_PLAN_PERIOD_END_DATE
  		FROM (
  			SELECT HVID,
  				MIN(PAYER_PLAN_PERIOD_START_DATE) AS PAYER_PLAN_PERIOD_START_DATE,
  				PAYER_PLAN_PERIOD_END_DATE,
  				COUNT(*) AS ENROLL_LINE_COUNT
  			FROM CTE_ENROLL_ENDS
  			GROUP BY HVID, PAYER_PLAN_PERIOD_END_DATE
  			) T2
  		JOIN @cdm_schema.PERSON P
  		ON T2.HVID = P.PERSON_SOURCE_VALUE
  	) T1
