/*PROCEDURE_OCCURRENCE*/

IF OBJECT_ID('@cdm_schema.PROCEDURE_OCCURRENCE') IS NOT NULL DROP TABLE @cdm_schema.[PROCEDURE_OCCURRENCE]
CREATE TABLE @cdm_schema.[PROCEDURE_OCCURRENCE]
WITH (
	CLUSTERED COLUMNSTORE INDEX,
	DISTRIBUTION = HASH(PERSON_ID)
)
AS
SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL)) AS PROCEDURE_OCCURRENCE_ID,
	PERSON_ID,
	CONCEPT_ID AS PROCEDURE_CONCEPT_ID,
	START_DATE AS PROCEDURE_DATE,
	TYPE_CONCEPT_ID AS PROCEDURE_TYPE_CONCEPT_ID,
	MODIFIER_CONCEPT_ID AS MODIFIER_CONCEPT_ID,
	QUANTITY AS QUANTITY,
	PROVIDER_ID,
	V.VISIT_OCCURRENCE_ID_NEW AS VISIT_OCCURRENCE_ID,
	SOURCE_VALUE AS PROCEDURE_SOURCE_VALUE,
	SOURCE_CONCEPT_ID AS PROCEDURE_SOURCE_CONCEPT_ID,
	QUALIFIER_SOURCE_VALUE
FROM @cdm_schema.STEM S
JOIN @cdm_schema.FINAL_VISIT_IDS V
  ON S.ID = V.STEM_ID
WHERE DOMAIN_ID = 'PROCEDURE'
