/*Step 2.2: Procedure codes without modifiers in MEDICAL_CLAIMS*/

SELECT
	CASE
		WHEN STAND1.TARGET_DOMAIN_ID IS NOT NULL
			THEN STAND1.TARGET_DOMAIN_ID
		ELSE 'Procedure'
	END AS DOMAIN_ID,
	P.PERSON_ID,
	PR.PROVIDER_ID,
	MC.CLAIM_ID+cast(MC.RECORD_ID as varchar(32))+DATA_FEED AS ID, --concat service line number to create a unique id
	CASE
		WHEN STAND1.TARGET_CONCEPT_ID IS NOT NULL
			THEN STAND1.TARGET_CONCEPT_ID
		ELSE 0
	END AS CONCEPT_ID,
	PROCEDURE_CODE AS SOURCE_VALUE,
	CASE
		WHEN SOURCE1.TARGET_CONCEPT_ID IS NOT NULL
			THEN SOURCE1.TARGET_CONCEPT_ID
		ELSE 0
	END AS SOURCE_CONCEPT_ID,
	CASE
		WHEN DATA_VENDOR = 'WEBMD'
			THEN 38000175
		WHEN DATA_VENDOR = 'Private Source 17'
			THEN 38000177
		ELSE 0
	END AS TYPE_CONCEPT_ID,
	DATE_SERVICE AS START_DATE,
	DATE_SERVICE_END AS END_DATE,
	NULL AS START_TIME,
	NULL AS DAYS_SUPPLY,
	0 AS DOSE_UNIT_CONCEPT_ID,
	NULL AS DOSE_UNIT_SOURCE_VALUE,
	NULL AS EFFECTIVE_DRUG_DOSE,
	NULL AS LOT_NUMBER,
	cast(NULL as varchar(50)) AS MODIFIER_SOURCE_VALUE,
	0 AS OPERATOR_CONCEPT_ID,
	0 AS QUALIFIER_CONCEPT_ID,
	NULL AS QUALIFIER_SOURCE_VALUE,
	NULL AS QUANTITY,
	NULL AS RANGE_HIGH,
	NULL AS RANGE_LOW,
	NULL AS REFILLS,
	0 AS ROUTE_CONCEPT_ID,
	NULL AS ROUTE_SOURCE_VALUE,
	NULL AS SIG,
	NULL AS STOP_REASON,
	NULL AS UNIQUE_DEVICE_ID,
	0 AS UNIT_CONCEPT_ID,
	NULL AS UNIT_SOURCE_VALUE,
	0 AS VALUE_AS_CONCEPT_ID,
	NULL AS VALUE_AS_NUMBER,
	NULL AS VALUE_AS_STRING,
	NULL AS VALUE_SOURCE_VALUE,
	0 AS ANATOMIC_SITE_CONCEPT_ID,
	0 AS DISEASE_STATUS_CONCEPT_ID,
	NULL AS SPECIMEN_SOURCE_ID,
	NULL AS ANATOMIC_SITE_SOURCE_VALUE,
	NULL AS DISEASE_STATUS_SOURCE_VALUE,
	0 AS MODIFIER_CONCEPT_ID
INTO @result_temp_table
FROM @source_schema.MEDICAL_CLAIMS MC
	LEFT JOIN @cdm_schema.SOURCE_TO_STANDARD AS STAND1
		ON PROCEDURE_CODE = STAND1.SOURCE_CODE_NO_DECIMAL
		AND STAND1.VOCAB_LABEL = 'PROCEDURES'
	LEFT JOIN @cdm_schema.SOURCE_TO_SOURCE AS SOURCE1
		ON PROCEDURE_CODE = SOURCE1.SOURCE_CODE_NO_DECIMAL
		AND SOURCE1.VOCAB_LABEL = 'PROCEDURES'
	JOIN @cdm_schema.PERSON P								/*~~~Check this join - we should be able to do an inner join here but leaving as left for now, also take out 'sample'~~~*/
		ON MC.HVID = P.PERSON_SOURCE_VALUE
		AND mc.HVID IS NOT NULL
		AND SUBSTRING(MC.HVID,1,@n_substring) = '@HVID_CHUNK'
	LEFT JOIN @cdm_schema.PROVIDER PR
		ON MC.PROV_RENDERING_NPI = PR.PROVIDER_SOURCE_VALUE

WHERE PROCEDURE_CODE IS NOT NULL AND PROCEDURE_MODIFIER_1 IS NULL
